version: 0.2

phases:
  pre_build:
      - echo nothing to downloaded
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install -DskipTest=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes
